version: '3.8'

networks:
  wirehole:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

services:
  unbound:
    hostname: unbound
    container_name: unbound
    image: mvance/unbound-rpi:latest
    mac_address: d0:ca:ab:cd:ef:01
    restart: always
    ports:
      - "53/tcp"
      - "53/udp"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    networks:
      wirehole:
        ipv4_address: 192.168.1.6

  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - unbound
    mac_address: d0:ca:ab:cd:ef:02
    restart: always
    environment:
      FTLCONF_REPLY_ADDR4: "192.168.1.5"  # should be same as internal service IP
      WEBPASSWORD: ""
      TZ: "Europe/Kiev"  # local time zone
      PIHOLE_DNS_: "192.168.1.6;8.8.8.8" #last 2 ip related to provider
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"  # WEB UI
    volumes:
      - "./pihole:/etc/pihole"
      - "./pihole/dnsmasq.d:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN
    networks:
      wirehole:
        ipv4_address: 192.168.1.5

  wireguard:
    hostname: wireguard
    container_name: wireguard
    image: weejewel/wg-easy
    depends_on:
      - unbound
      - pihole
    mac_address: d0:ca:ab:cd:ef:03
    restart: always
    environment:
      - WG_HOST=78.27.136.216 # external IP of your server
      - WG_PORT=51820
      - WG_DEFAULT_DNS=192.168.1.5
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - ./wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wirehole:
        ipv4_address: 192.168.1.7
